# Site settings
title: Arlo Herrine
email: arloherrine@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Programmer of code
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arloherrine.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
